### ISSUE TITLE
I got ubuntu to work but this is what happens when i use ubuntu ls /root/.bind 

### ISSUE THREAD

**Issue by roanokee** [ng1nX4O4/Tmux-Bunch#3]
![Screenshot_20190822-001325_Termux](https://user-images.githubusercontent.com/47486509/63487695-decf8000-c471-11e9-93ef-2d0b822457c9.jpg)

**Comment by ng1nX4O4** [comment]
Can I Have The Output Of `java -version` & `apktool --version`
