### ISSUE TITLE
apk binding error

### ISSUE THREAD

**Issue by Isururanjana** [ng1nX4O4/Tmux-Bunch#4]
![Screenshot_2019-08-25-22-08-57](https://user-images.githubusercontent.com/54226767/63653080-c28b5600-c785-11e9-9ca6-bfc87b383667.png)
Solution plzzzzzx

**Comment by ng1nX4O4** [comment]
Okkk Let Me See

**Comment by ng1nX4O4** [comment]
Can I Have The apk file

**Comment by ng1nX4O4** [comment]
Please Use this tool instead

Http://github.com/ng1nX4O4/PatchApk

**Comment by Isururanjana** [comment]
Thanx for information sir.but another error.see

**Comment by Isururanjana** [comment]
![Screenshot_2019-08-27-20-04-59](https://user-images.githubusercontent.com/54226767/63780899-7fa4bc00-c906-11e9-8b81-8ed58ffe98bd.png)

**Comment by Isururanjana** [comment]
Can u please help , how can I install sign apk?

**Comment by ng1nX4O4** [comment]
can i have the working directory of metasploit-framework

**Comment by ng1nX4O4** [comment]
Fixed Everything Can You Please Use The Update Script. And Setup It Again

**Comment by ng1nX4O4** [comment]
Use Latest Version Of PatchApk
